### ISSUE TITLE
How to unit test this?

### ISSUE THREAD

**Issue by dingo-d** [schlessera/wcbtn-2018-api#4]
I am adopting the factory method and instantiating my services in a plugin like you did in the [Plugin.php](https://github.com/schlessera/wcbtn-2018-api/blob/master/src/Plugin.php#L161) file, and I stuck in a rut a bit when it comes to unit testing the code.

For PluginFactory I can just do (in the test method)

```php
$this->assertInstanceOf( Plugin::class, Plugin_Factory::create() );
```

And this is ok, as the plugin factory must return an instance of a `Plugin` class.

But when I want to test any public method inside the `Plugin.php` file, I'm having some troubles.

Ideally, I'd mock a simple Plugin with maybe one service - using Mockery that would be like

```php
// namespaces are defined...

\Mockery::mock( new Plugin ); // using proxied partial test double since the Plugin is a final class
```

But how would I use it when I need to test `PluginFactory::create()->activate();` method? Is defining a mock plugin in the `setUp` method enough?

**Comment by schlessera** [comment]
You don't want to test `PluginFactory::create()->activate();`, as that cannot possibly be a unit test (testing `PluginFactory::create()` & `Plugin::activate()` at the same time).

What you want to test is `Plugin::activate()` only instead. In unit tests, you test one class only, and instantiate it directly. The mocks are used for injecting dependencies if the class under test requires them.

So this would then be something like this:

```php
public function test_it_can_be_activated() {
   // 1 - Arrange
   $mockAssetsHandler = Mockery::mock( AssetsHandler::class );
   $plugin = new Plugin( $mockAssetsHandler );

   // 2 - Act
   $plugin->activate();

   // 3 - Assert
   $this->assertSomething( $result );
}
```


And generally, there's often not much of a point testing factories. You should focus on testing complex logic instead, factories are always very simplistic.

**Comment by dingo-d** [comment]
Oh, that makes much more sense. I was under the impression that I'd take the smallest unit of test I can (a public method in a class in this instance) and test every one in a class.

I got the feeling that testing factories make little sense, and I'm almost more inclined to switch to just do integration testing instead of unit tests, but the requirement I got from the above that my code should have 90% code coverage 😬
