### ISSUE TITLE
Passing dependencies in the services?

### ISSUE THREAD

**Issue by dingo-d** [schlessera/wcbtn-2018-api#5]
One thing I noticed is that services are all 'pure' classes. Pure in the sense that they hold no constructor and there are no injected dependencies in them.

Is the reasoning behind this the fact that every service is a kinda self-contained unit that only needs to `register()` something (in most cases adding of actions and filters)?

And then, any dependency injection that happens, happens when you call a certain class in a method.

This is to ensure less coupling in the code?

**Comment by schlessera** [comment]
No, this just because this simplified code that is meant to educate a certain concept. There is no dependency injector in use. There are a few instances of setter injection (instead of constructor injection) but that's it.

**Comment by dingo-d** [comment]
So one could never use constructor DI inside services with this approach? But that's not a bad thing, right? Setter injection is fine to use. 

I'm just looking for a way to write my plugin code better, and I like this approach where I have SRP honored for each class - one class for creating menus will handle all the business logic and pass needed arguments to the view, everything is neat and logical.

**Comment by schlessera** [comment]
Oh, you certainly can use constructor injection. You will just have to stick to one of the following four approaches:

1. Have the exact same constructor signature for all services. Pretty much a non-starter, as that defeats the purpose of dependency injection)
2. Have a way of mapping dependencies to constructor arguments. This is what a dependency injection container usually does, by using the constructor arguments' typehints through Reflection.
3. Manually instantiate each service individually to tailor the depencencies on a case-by-case basis.

Number 3. is cleanest for smaller projects, and you can hide this within a factory.

Number 2. is the more scalable approach, but comes with an additional layer of abstraction that might make debugging more difficult. I'm usually using this one in my projects: https://github.com/brightnucleus/injector. However, I've playing with the thought of moving this over to the one from Symfony 4.

Alternatively, you could also look into using something like this for smaller projects: https://github.com/brightnucleus/invoker/blob/master/src/InstantiatorTrait.php
It allows you to pass an associative array of dependencies to the invoker and it will then use whatever is needed to instantiate the given class, based on the argument names, not their typehints.

**Comment by dingo-d** [comment]
I'll definitely look at the suggested links, thank you so much for helping out 👍
